development:
  adapter: postgresql
  database: dsocialnetwork_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
  username: iacobson
  password:

test:
  adapter: postgresql
  database: dsocialnetwork_test
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
  username: iacobson
  password:

production:
  adapter: postgresql
  database: dsocialnetwork_production
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
